#!/bin/bash
# ALIASES

## Distro dependent aliases

grep --quiet Gentoo /proc/version
GENTOO=$?

# Power commands
alias poweroff='sudo poweroff'
alias reboot='sudo reboot'
alias hibernate='systemctl hibernate'
alias suspend='systemctl suspend'
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'

if [ $GENTOO -eq 0 ]; then
	alias markdown='markdown_py'
	alias sdc='sudo dispatch-conf'
else
	alias wifi-menu='sudo wifi-menu'
	alias netcfg='sudo netcfg'
	alias netcfg-menu='sudo netcfg-menu'
fi

## Linux commangs
alias grep='grep --color=auto'
alias ls='ls -X --color=auto'
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias c='clear'
alias cp='cp -i'
alias mv='mv -i'
alias cdl=cd_last_dir
alias cd=cd_and_ls
alias ffind='find . -iname'

## Typo aliases
alias s=ls
alias cd..="cd .."
alias cd...="cd ../.."

## Utilities
alias fuck='sudo $(fc -ln -1)'
alias ungcc="gcc -z execstack -fno-stack-protector -fno-pie"
alias ocvc="g++ \`pkg-config opencv --cflags --libs\`"
alias runonce="$STUFF/scripts/run_once.sh"
alias nvidiaoff="sudo $STUFF/scripts/nvidiaoff.sh"
alias fixjava="wmname LG3D"
alias irc="(sleep 10 && bash $STUFF/scripts/run_once.sh notify-listener.py $STUFF/scripts/notify-listener.py > /dev/null 2>&1) & irssi"
alias mkd="$STUFF/scripts/mkd.sh"
alias initlatex="mkdir tmp; mkdir bib; touch bib/bib.bib; cp $STUFF/templates/template.tex main.tex; touch main.tex.latexmain"
alias initc="mkdir src; cp $STUFF/templates/Makefile.c ./Makefile"
alias pass="/bin/true"
alias to_c_string="hexdump -v -e '\"\\\\\\x\" 1/1 \"%02x\"'"
alias machete="sudo kill -9"

#alias lsize="ls -lR | grep -e "^-" | awk '{sum+=\$5} END {if [ $A ] ; then if [ $A = \"K\" ] ; then print sum/1024 ; elif [ $A = \"M\" ] ; then print sum/1024/1024 ; elif [ $A = \"G\" ] ; then print sum/1024/1024/1024 ; else ; print sum ; fi ; else ; print sum ; fi'}"

## Mount
alias dlist="udisks --enumerate-device-files"
alias dmount="udisksctl mount -b"
alias dumount="udisksctl unmount -b"

## Folders
alias uni='\cd ~/Dropbox/University'
alias prj='\cd ~/Dropbox/Projects'
alias sec='\cd ~/Dropbox/IT/Security'
alias drp='\cd ~/Dropbox'
alias gtd='\cd /mnt/shared/gtd/'

## Git
alias gc='git commit -m'
alias gca='git commit --amend'
alias gcheck='git checkout'
alias ga='git add'
alias gaa='git add --all'
alias gap='git add --patch'
alias gpa='git_push_all'
alias gp='git push'
alias gpo='git push origin'
alias gpom='git push origin master'
alias gplo='git pull origin'
alias gplom='git pull origin master'
alias gfo='git fetch origin'
alias gfom='git fetch origin master'
alias grfh='git rebase FETCH_HEAD'
alias gst='git status'
alias gsa='git stash apply'
alias gss='git stash save'
alias gd='git diff'
alias grm="git ls-files -deleted | xargs git rm"

## Shell dependent

[[ $SHELL =~ ".*zsh.*" ]] && alias gdb='SHELL=/bin/bash gdb'
