#!/bin/bash

grep --quiet Gentoo /proc/version
GENTOO=$?

if [ -n "$DISPLAY" ]; then
	export BROWSER=google-chrome
	if [ $GENTOO -eq 0 ]; then
		export TERMINAL=/usr/bin/urxvt
	else
		export TERMINAL=/usr/bin/gnome-terminal
	fi
fi

export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
export MOZILLA_FIVE_HOME="/usr/lib/firefox"
export XDG_CONFIG_HOME="$HOME/.config"


if [ $GENTOO -eq 0 ]; then
	PATH=$PATH:$HOME/.gem/ruby/1.9.1/bin:$HOME/.dropbox-dist/
else
	PATH=$PATH:$HOME/.gem/ruby/2.0.0/bin
fi

export PATH=$PATH:/opt/eclipse:/opt/MATLAB/R2012a/bin
