#!/bin/bash

grep --quiet Gentoo /proc/version
GENTOO=$?

if [ -n "$DISPLAY" ]; then
	export BROWSER=google-chrome
	#if [ $GENTOO -eq 0 ]; then
  export TERMINAL=/usr/bin/terminator
	#else
		#export TERMINAL=/usr/bin/gnome-terminal
	#fi
fi

export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
export MOZILLA_FIVE_HOME="/usr/lib/firefox"
export XDG_CONFIG_HOME="$HOME/.config"
export WINEDLLOVERRIDES='winemenubuilder.exe=d'

if [ $TERM = "linux" ]; then
  export TERM="fbterm"
fi

if [ $TERM = "xterm" ]; then
  export TERM="xterm-256color"
fi

export PATH="$PATH:$STUFF/bin:$HOME/.gem/ruby/current/bin"
eval `dircolors $HOME/.dir_colors`
stty -ixon
