#!/bin/bash

git_push_all() {
  if [ $# -gt 0 ] ; then
    ARGS="$@"
  else
    ARGS=$(git branch | cut -c 3-)
  fi
  for r in `git remote` ; do
    git push $r $ARGS
  done
}

save_dir() {
	pwd > ~/.lastdir	
}

cd_last_dir() {
	\cd "`cat ~/.lastdir`"
}

cd_and_ls() {
  \cd $@
  if [[ $(ls -C | wc -l) -lt 30 ]] ; then
    ls --color=auto -X
  else
    echo -e "\e[0;31mLots of items...\e[0m"
  fi
}
