#!/bin/bash

git_push_all() {
  if [ $# -gt 0 ] ; then
    BRANCH=$1
  else
    BRANCH=master
  fi
  for r in `git remote` ; do
    git push $r $BRANCH
  done
}

save_dir() {
	pwd > ~/.lastdir	
}

cd_last_dir() {
	cd "`cat ~/.lastdir`"
}

cd_and_ls() {
  cd $@
  ls --color=auto -X
}
