#!/bin/bash

git_push_all() {
  if [ $# -gt 0 ] ; then
    BRANCH=$1
  else
    BRANCH=master
  fi
  for r in `git remote` ; do
    git push $r $BRANCH
  done
}

save_dir() {
	pwd > ~/.lastdir	
}

cd_last_dir() {
	cd "`cat ~/.lastdir`"
}

cd_and_ls() {
  cd $@
  if [[ $(ls -l | wc -l) -lt 30 ]] ; then
    ls --color=auto -X
  else
    echo -e "\e[0;31mLots of items...\e[0m"
  fi
}
