#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xset -b
xcompmgr -c &
eval $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
#export GNOME_KEYRING_PID
#export GNOME_KEYRING_SOCKET
export SSH_AUTH_SOCK
export GPG_AGENT_INFO
export _JAVA_AWT_WM_NONREPARENTING=1

source ~/.linux_stuff
xsetroot -cursor_name left_ptr
#setxkbmap it us
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources
[[ -f $STUFF/X/Xmodmap ]] && xmodmap $STUFF/X/Xmodmap

grep --quiet Gentoo /proc/version
GENTOO=$?

PARAMS=""
#if [ $GENTOO -eq 0 ]; then
##	PARAMS="ck-launch-session dbus-launch --sh-syntax --exit-with-session"
##PARAMS="dbus-launch --sh-syntax --exit-with-session"

#fi

if [ -z "$1" ]
then
  WM=xmonad
else
  WM=$1
fi

exec $PARAMS $WM
