#!/bin/zsh


# { Modules

zmodload zsh/pcre
setopt no_case_match

# }

# { Configuration / Variables

local sess_name="irssi"

# }

# { Functions

function usage() {
  echo "irssi_daemon [start|stop|help]"
  return 0
}

function start() {
  tmux new-session -d -s ${sess_name} 'irssi'
  tmux split-window -t ${sess_name} -h -l 20 'cat ~/.irssi/nicklistfifo'
  return $?
}

function attach() {
  tmux -L default attach-session -t ${sess_name}
}

function stop() {
  tmux kill-session -t ${sess_name}
  return $?
}

# }

# { Entry point

if [[ $# -ne 1 ]]; then
  echo "A subcommand should be given"
  usage
  exit -1
else
  if ! which /usr/bin/tmux > /dev/null || ! which /usr/bin/irssi > /dev/null; then
    echo "Missing dependencies: tmux and irssi are needed."
    exit -2
  fi

  if [[ $1 -pcre-match "attach" ]]; then
    attach
    exit $?
  fi

  if [[ $1 -pcre-match "start" ]]; then
    start
    exit $?
  fi

  if [[ $1 -pcre-match "stop" ]]; then
    stop
    exit $?
  fi

  if [[ $1 -pcre-match "help|usage" ]]; then
    usage
    exit $?
  fi

  echo "Invalid command given."
  usage
  exit -3
fi

# }


# vim: set ft=zsh:ts=2:sw=2
