#
# ~/.zprofile
#

source $HOME/.linux_stuff

if $(tty | grep --quiet tty) ; then
  # TTY!
  export IM_CONSOLE=1
  source $STUFF/scripts/console_autostart.sh
  echo "Starting GPG agent"
  eval $(/usr/bin/gpg-agent --daemon --enable-ssh-support)
  echo "Launching FBTERM"

  # fbterm-bi: a wrapper script to enable background image with fbterm
  # usage: fbterm-bi /path/to/image fbterm-options
echo -ne "\e[?25l" # hide cursor
fbv -ciuker "$HOME/Pictures/wallpaper_term" << EOF
q
EOF
#shift
export FBTERM_BACKGROUND_IMAGE=1
exec fbterm "$@"

fi

if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
  export IM_SSH=1
fi

[[ -f ~/.bash_profile ]] && . ~/.bash_profile
[[ -f ~/.zshrc ]] && . ~/.zshrc
